image: registry.nexdev.net:5050/docker/docker-engine/docker:19.03.14

stages:
  - build
  - post-build

include:
  - project: 'ci/common-ci'
    ref: rocketor
    file: 'rocketor-integration/rules/index.gitlab-ci.yml'
  - project: 'ci/common-ci'
    ref: rocketor
    file: 'docker/base/build-docker-image.gitlab-ci.yml'
  - project: 'ci/common-ci'
    ref: rocketor
    file: 'docker/base/post-build-docker-image.gitlab-ci.yml'

variables:
  PROJECT_ROOT_PATH: .
  DOCKER_IMAGE_PATH: nexcel/nexops/deployment-api
  DOCKER_FILE_PATH: ./
  DOCKER_FILE_NAME: Dockerfile
  CONFIG_FILE_PATH: ./src
  CONFIG_FILE_NAME: configs
  CONFIG_FILE_EXTENSION: js

before_script:
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - echo -e "${SSH_PRIVATE_KEY_1}\n${SSH_PRIVATE_KEY_2}\n${SSH_PRIVATE_KEY_3}" | ssh-add -
  - export DEPLOY_ENV=$CI_ENVIRONMENT_NAME;
  - export CI_REGISTRY_IMAGE=$DOCKER_REG_URL/$DOCKER_IMAGE_PATH
  - export CI_REGISTRY_IMAGE_VERSION=${CI_COMMIT_SHA:0:8}
  - echo $CI_REGISTRY_IMAGE
  - export CONFIG_FILE=$CONFIG_FILE_NAME.${DEPLOY_ENV}.$CONFIG_FILE_EXTENSION;
  - export CONFIG_DEST_FILE=$CONFIG_FILE_NAME.$CONFIG_FILE_EXTENSION;
  - cp $CONFIG_FILE_PATH/$CONFIG_FILE $CONFIG_FILE_PATH/$CONFIG_DEST_FILE

build:local:
  extends: 
    - .build:default:image
  environment:
    name: LOCAL

post:build:local:
  needs: ['build:local']
  extends: 
    - .post_build
  environment:
    name: LOCAL

build:prod:
  extends: 
    - .build:default:image
  environment:
    name: PROD

post:build:prod:
  needs: ['build:prod']
  extends: 
    - .post_build
  environment:
    name: PROD