---
- name: Verify stacks directory exists (on first swarm node)
  when: inventory_hostname in groups['swarm_managers']
  file:
    path: "/home/{{ansible_user}}/stacks"
    state: directory

- name: Create directory
  file:
    path: "{{gluster_path}}/deployment-api"
    mode: "0755"
    state: directory
  become: yes

# - name: Copy src file
#   synchronize:
#     src: "files/src-code"
#     dest: /home/{{ansible_user}}/stacks/src-code
#   become: yes

# - name: Build an image and push it to a private repo
#   run_once: true
#   docker_image:
#     path: /home/{{ansible_user}}/stacks/src-code
#     name: registry.nexdev.net:5050/nexcel/nexops/deployment-api
#     tag: latest
#     push: yes

- name: Copy docker-compose file
  template:
    src: "templates/docker-compose.yml.j2"
    dest: /home/{{ansible_user}}/stacks/deployment-api-stack.yml
  become: yes

- name: Build up and run container
  shell: |
    cd /home/{{ansible_user}}/stacks
    docker stack deploy --compose-file=deployment-api-stack.yml --with-registry-auth nexops
  become: yes
